version: "3.9"

services:
  backend_db:
    container_name: backend_db
    image: mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
  backend_pma:
    container_name: backend_pma
    image: phpmyadmin/phpmyadmin
    links:
      - backend_db
    environment:
      PMA_HOST: backend_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8082:80
    networks:
      - backend
networks:
  backend:
    name: backend